### ISSUE TITLE
Can't find host

### ISSUE THREAD

**Issue by twastvedt** [hardillb/nginx-proxy-avahi-helper#4]
Hi! Thanks for putting this together. I have everything running, but can't ping or otherwise resolve the hosts from other machines. I'm very new to mdns, so I'm not sure what to look for or how to interpret what I have found.

avahi-helper log:
```
dockergen.1 | 2022/04/03 16:52:54 Received event die for container 94a004be6d7e
dockergen.1 | 2022/04/03 16:52:55 Received event stop for container 94a004be6d7e
dockergen.1 | 2022/04/03 16:52:55 Generated 'cnames' from 7 containers
dockergen.1 | 2022/04/03 16:52:55 Running '/usr/src/app/restart.sh'
cname.1    | INFO: Exiting on SIGTERM...
dockergen.1 | 2022/04/03 16:52:55 Contents of cnames did not change. Skipping notification '/usr/src/app/restart.sh'
forego     | starting cname.1 on port 5200
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to cname.1
dockergen.1 | 2022/04/03 16:52:56 Received signal: terminated
```

Let's say one of those virtual hosts is `test.local`.

```
$ hostname
pi
$ avahi-resolve -n pi.local
pi.local     172.23.0.1
$ avahi-resolve -nv6 pi.local
Server version: avahi 0.7; Host name: pi.local
pi.local     fe80::c401:bdff:fe96:af0f
$ avahi-resolve -n test.local
pi.local     fe80::c401:bdff:fe96:af0f
$ avahi-resolve -n4 test.local
Failed to resolve host name 'test.local': Timeout reached
```
Note that the hostname and the virtual host resolve to the same v6 ip address, but the virtual host fails to resolve a v4 version. Not sure if that's significant or an issue.

On another machine:
```
$ ping test.local
Ping request could not find host test.local. Please check the name and try again.

$ ping pi.local

Pinging pi [192.168.68.64] with 32 bytes of data:
Reply from 192.168.68.64: bytes=32 time=5ms TTL=64
...
```

Where should I go from here? Thanks!

**Comment by techiebod** [comment]
Had the same issue, after much head scratching I read the other issue here and saw the link to https://github.com/edgexfoundry-holding/device-bluetooth-c/issues/4 -- long answer very short, the issue is that writing to the dbus socket requires escalated privileges, so "privileged: true" is needed (that's in the docker-compose format, I'm assuming you can transpose to your way of running it).  Or at least that worked for me :)

Must be said this repo is way out of date, and rebuilding it is hard (for a docker noob like me at least) due to obsolete dependancies

**Comment by twastvedt** [comment]
@techiebod Thanks for the tip! I did that, and now the container output looks much more promising. However, the results to the test commands above (avahi-resolve and ping) have the same output. Even though this container reports success, I am not able to resolve the cnames from other machines on the network. Any other thoughts? You said it's working for you, so after starting this container, you can successfully ping (or visit) the urls in the `VIRTUAL_HOST` environment variable values on your other containers? Thanks!

**Comment by techiebod** [comment]
Yep, all works for me, with the following docker-compose config:

```
avahi-proxy:
    container_name: avahi-proxy
    image: hardillb/nginx-proxy-avahi-helper
    privileged: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:rw
    restart: always
```

And then a container setup like this (some lines removed for brevity):
```
homer:
    image: b4bz/homer
    environment:
      - VIRTUAL_HOST=blackbox.local
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
```
   
So with the above on another machine (i.e. not the host or container) I can ping blackbox.local for example.

To test your local Avahi setup you can do the same from the commandline with: `avahi-publish -a -R blah.local <host-ip>`

Which whilst it runs, should allow you to ping blah.local from another machine.

Or if you prefer (on a mac) run: `dns-sd -G v4 blah.local`

HTH
